version: "3.9"
services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: booklending
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookleading
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  db_data: